### ISSUE TITLE
Getting error on Chrome

### ISSUE THREAD

**Issue by alarmatwork** [ryanmcgrath/wii-js#3]
Found this interesting project, when I trying to run the demo, I'm getting with the latest Chrome on Macos, Wii connected to bluetooth:

Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
(index):73 Uncaught ReferenceError: Wii is not defined
    at (index):73
(anonymous) @ (index):73

Would be really cool to use Wiimote acceleration data as an input to machine learning project.

**Comment by ryanmcgrath** [comment]
This lib was meant for the built-in browser (Opera) running _on_ the Wii. It was never expected to work in a PC browser.

You likely want some bluetooth lib/custom code for this.
